### ISSUE TITLE
Cannot use both Docker and Nix at the same time

### ISSUE THREAD

**Issue by photonsphere-org** [sarthakbagaria/web-push#5]
A `stack build` results in the following error message when using Nix:
```
$ stack build
UnliftIO.Exception.throwString called with:

Cannot use both Docker and Nix at the same time
Called from:
  throwString (src/Stack/Runners.hs:108:21 in stack-2.7.1-IKhLtcyrcbGCjzePWCOXpj:Stack.Runners)
```

Which can be fixed by inserting a `nix disable` in `stack.yaml` (under the `docker enable`); the updated `stack.yaml` section is as follows:
```
docker:
    enable: true

# <--- this section inserted
nix:
    enable: false  
```

Alternatively use the following command to initiate a build:
```sh
stack build --docker --no-nix
```
